version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: ./Docker/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}?schema=public
    container_name: ${CONTAINER_NAME}
  db:
    image: 'postgres:16'
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    container_name: ${CONTAINER_NAME_DB}
